-- Tabla DEPT
CREATE TABLE dept (
  DEPTNO INT NOT NULL,
  DNAME VARCHAR(14),
  LOC VARCHAR(13),
  PRIMARY KEY (DEPTNO),
  UNIQUE (DNAME)
);

-- Tabla EMP
CREATE TABLE emp (
  EMPNO INT NOT NULL,
  ENAME VARCHAR(10),
  JOB VARCHAR(9),
  MGR INT,
  HIREDATE DATE,
  SAL DECIMAL(7,2),
  COMM DECIMAL(7,2),
  DEPTNO INT,
  PRIMARY KEY (EMPNO),
  FOREIGN KEY (DEPTNO) REFERENCES dept(DEPTNO)
);

-- Índice en ENAME
CREATE INDEX Idx_Ename ON emp(ENAME);

-- Tabla PRO
CREATE TABLE pro (
  PRONO INT NOT NULL,
  PNAME VARCHAR(10),
  LOC VARCHAR(13),
  DEPTNO INT,
  PRIMARY KEY (PRONO),
  FOREIGN KEY (DEPTNO) REFERENCES dept(DEPTNO)
);

-- Tabla EMPPRO
CREATE TABLE emppro (
  EMPNO INT NOT NULL,
  PRONO INT NOT NULL,
  HOURS INT,
  FOREIGN KEY (EMPNO) REFERENCES emp(EMPNO),
  FOREIGN KEY (PRONO) REFERENCES pro(PRONO)
);

