
-- -----------------------------------
-- Primary KEY
-- -----------------------------------

ALTER TABLE job_grades  ADD PRIMARY KEY (Grade_Level);
ALTER TABLE jobs        ADD PRIMARY KEY (JOB_ID);
ALTER TABLE regions     ADD PRIMARY KEY (REGION_ID);

ALTER TABLE countries   ADD PRIMARY KEY (COUNTRY_ID),
                                ADD KEY REGION_ID_IX   (REGION_ID);

ALTER TABLE locations   ADD PRIMARY KEY (LOCATION_ID),
								ADD KEY LOC_COUNTRY_IX (COUNTRY_ID);

-- manager-id
ALTER TABLE departments ADD PRIMARY KEY (DEPARTMENT_ID), 
                                ADD KEY DEPT_LOCATION_IX (LOCATION_ID),
								ADD KEY DEPT_MGR_FK (MANAGER_ID); 
-- employee-id
ALTER TABLE job_history ADD PRIMARY KEY (EMPLOYEE_ID,START_DATE),
                                ADD KEY JHIST_DEPARTMENT_IX (DEPARTMENT_ID),
								ADD KEY JHIST_EMPLOYEE_IX (EMPLOYEE_ID),
								ADD KEY JHIST_JOB_IX (JOB_ID); 

-- manager-id
ALTER TABLE employees   ADD PRIMARY KEY (EMPLOYEE_ID), 
                                ADD KEY EMP_DEPARTMENT_IX (DEPARTMENT_ID),
								ADD KEY EMP_JOB_IX (JOB_ID),
								ADD KEY EMP_MANAGER_IX (MANAGER_ID), 

								ADD KEY EMP_NAME_IX (LAST_NAME,FIRST_NAME);

-- -----------------------------------
-- Constraint 
-- -----------------------------------

ALTER TABLE countries
ADD CONSTRAINT countries_ibfk_1 FOREIGN KEY (REGION_ID) REFERENCES regions (REGION_ID);

ALTER TABLE locations
ADD CONSTRAINT LOC_C_ID_FK FOREIGN KEY (COUNTRY_ID) REFERENCES countries (COUNTRY_ID);

ALTER TABLE departments
ADD CONSTRAINT DEPT_LOC_FK FOREIGN KEY (LOCATION_ID) REFERENCES locations (LOCATION_ID),
ADD CONSTRAINT DEPT_MGR_FK FOREIGN KEY (MANAGER_ID)  REFERENCES employees (EMPLOYEE_ID);

ALTER TABLE job_history
ADD CONSTRAINT JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments (DEPARTMENT_ID),
ADD CONSTRAINT JHIST_EMP_FK  FOREIGN KEY (EMPLOYEE_ID)   REFERENCES employees (EMPLOYEE_ID),
ADD CONSTRAINT JHIST_JOB_FK  FOREIGN KEY (JOB_ID)        REFERENCES jobs (JOB_ID);

ALTER TABLE employees
ADD CONSTRAINT EMP_DEPT_FK    FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments (DEPARTMENT_ID),
ADD CONSTRAINT EMP_JOB_FK     FOREIGN KEY (JOB_ID)        REFERENCES jobs (JOB_ID),

ADD CONSTRAINT EMP_MANAGER_FK FOREIGN KEY (MANAGER_ID)    REFERENCES employees (EMPLOYEE_ID);
 


